
services:
  elasticsearch_anime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch_anime
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # Sesuaikan memori sesuai kebutuhan
      - "xpack.security.enabled=false"  # Menonaktifkan keamanan
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata_bg:/usr/share/elasticsearch/data

volumes:
  esdata_bg:
    driver: local
