###  AUTO COMPLITE
GET http://localhost:8080/autocomplete?q=One%20Piece
Accept: application/json
Content-Type: application/json
### AUTO COMPLITE
GET http://localhost:8080/autocomplete?q=sousou
Accept: application/json
Content-Type: application/json




### SEACRCH
GET http://localhost:8080/search/anime?name=One+Piece&from=0&size=20&genre=Comedy
Accept: application/json
Content-Type: application/json
### SEARCH ONLY GENRE
GET http://localhost:8080/search/anime?genre=Comedy
Accept: application/json
Content-Type: application/json
### SEARCH ONLY NAME
GET http://localhost:8080/search/anime?name=Sousou no Frieren
Accept: application/json
Content-Type: application/json
### SEARCH WITH MIN RATING
GET http://localhost:8080/search/anime?min_score=8
Accept: application/json
Content-Type: application/json






### TOP ANIME
GET http://localhost:8080/anime/top?top_year=2022
Accept: application/json
Content-Type: application/json

### find by id
GET http://localhost:8080/anime/100
Accept: application/json
Content-Type: application/json

### find recomend by id, 1page 10 data bg
GET http://localhost:8080/anime/100/recommend?page=1
Accept: application/json
Content-Type: application/json




### CREATE NEW USER
POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
  "username": "hanniPham",
  "email": "hannih@gmail.com",
  "password": "hanni72"
}

### CHANGE PASS
POST http://localhost:8080/users/change
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzM3Mjg4NTJ9.KnkzzBZN_pV_2-PFzrCn9frdKBz-k8xmq_xvVi6fGIY

{
  "email": "hannih@gmail.com",
  "new_password": "hannikuh"
}

### CONFIRMATION CHANGE
POST http://localhost:8080/users/change-confirm
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzM3Mjg4NTJ9.KnkzzBZN_pV_2-PFzrCn9frdKBz-k8xmq_xvVi6fGIY

{
  "token": "f5a21a349410f24c1fa77572ffb3c69aafba7bc5a4c81941c8c2cb2800e7b638"
}

### LOGIN TEST
POST http://localhost:8080/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "hannih@gmail.com",
  "password": "hannikuh"
}

### LOGIN TEST
POST http://localhost:8080/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "himmel@gmail.com",
  "password": "himmel"
}


### ADD FAV
POST http://localhost:8080/users/fav/72
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzM2NzgxMzd9.kY8wzBOR3AnVo7WyBbQ4xIeXdU3WZ-tYZqx7ZRv4_vM

### ADD FAV
DELETE http://localhost:8080/users/fav/1000
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzM2NzczODZ9.3WupZCRlcIIUKKlhwY7ARNnq24im40sNpjqc76t5Zao


### LIST FAV
GET http://localhost:8080/users/fav
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzM2ODA1ODl9.AaptFTpONKnbBNOGuB7ilI0XWty7pQNy-UUoEFE1fc4

