###  AUTO COMPLITE
GET http://localhost:8080/autocomplete?q=One%20Piece
Accept: application/json
Content-Type: application/json
### AUTO COMPLITE
GET http://localhost:8080/autocomplete?q=sousou
Accept: application/json
Content-Type: application/json




### SEACRCH
GET http://localhost:8080/search/anime?name=One+Piece&from=0&size=20&genre=Comedy
Accept: application/json
Content-Type: application/json
### SEARCH ONLY GENRE
GET http://localhost:8080/search/anime?genre=Comedy
Accept: application/json
Content-Type: application/json
### SEARCH ONLY NAME
GET http://localhost:8080/search/anime?name=Sousou no Frieren
Accept: application/json
Content-Type: application/json
### SEARCH WITH MIN RATING
GET http://localhost:8080/search/anime?min_score=8
Accept: application/json
Content-Type: application/json






### TOP ANIME
GET http://localhost:8080/anime/top?top_year=2022
Accept: application/json
Content-Type: application/json

### find by id
GET http://localhost:8080/anime/100
Accept: application/json
Content-Type: application/json

### find recomend by id, 1page 10 data bg
GET http://localhost:8080/anime/100/recommend?page=1
Accept: application/json
Content-Type: application/json




### CREATE NEW USER
POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
  "username": "koriebruh",
  "email": "koriebruh@gmail",
  "password": "korie123"
}

### CREATE NEW USER
POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
  "username": "himmell",
  "email": "himmel@gmail",
  "password": "himmel"
}

### LOGIN TEST
POST http://localhost:8080/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "himmel@gmail",
  "password": "himmel"
}


### ADD FAV
POST http://localhost:8080/users/fav/123
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzM2NzcyMTJ9.79CtQZaxm_8Mf0dvKQZeQWoemhDnuDZyEvvh6Q-bfl0

### ADD FAV
DELETE http://localhost:8080/users/fav/123
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzM2NzczODZ9.3WupZCRlcIIUKKlhwY7ARNnq24im40sNpjqc76t5Zao

