###  AUTO COMPLITE
GET http://localhost:8080/autocomplete?q=One%20Piece
Accept: application/json
Content-Type: application/json
### AUTO COMPLITE
GET http://localhost:8080/autocomplete?q=Naruto
Accept: application/json
Content-Type: application/json





### GET request to example server
GET http://localhost:8080/
Accept: application/json
Content-Type: application/json

### GET request to example server
GET http://localhost:8080/search/anime?query=Naruto&page=1&limit=10&genre=Action&status=Ongoing&min_score=7
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/search/anime?query=Naruto&page=1&limit=10
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/search/anime?genre=Comedy
Accept: application/json
Content-Type: application/json


### BISA
GET http://localhost:8080/search/anime?query=Naruto&page=1&limit=20&genre=Action&status=Finished%20Airing&min_score=8
Accept: application/json
Content-Type: application/json

###

# curl -X GET "http://localhost:8080/search/anime?query=Naruto&page=1&limit=20&genre=Action&status=Finished%20Airing&min_score=7.99" -H "Accept: application/json"
GET http://localhost:8080/search/anime?query=Naruto&page=1&limit=20&genre=Action&status=Finished%20Airing&min_score=7.99
Accept: application/json

###

###
GET http://localhost:8080/search/anime?name=One+Piece&from=0&size=20&genre=Comedy

###
GET http://localhost:8080/anime/100

###


